ordererOrgs:
  - domain: orderer.dns.com
    mspId: orderer
    specs:
      - host: orderer0
        port1: 11001
        port2: 12001
        port3: 13001
      - host: orderer1
        port1: 11002
        port2: 12002
        port3: 13002
      - host: orderer2
        port1: 11003
        port2: 12003
        port3: 13003
peerOrgs:
  - domain: org1.dns.com
    mspId: org1
    specs:
      - host: peer0
        port1: 11005
        port2: 12005
        port3: 13005
#  - domain: org0.dns.com
#    mspId: org0
#    specs:
#      - host: peer0
#        port1: 11004
#        port2: 12004
#        port3: 13004

